services:
    app:
        build:
            context: .
        ports:
            - 8000:8000
        volumes:
            - .:/var/www
        depends_on:
            - db
        environment:
            DB_HOST: db
            DB_DATABASE: laravel
            DB_USERNAME: root
            DB_PASSWORD: root
        working_dir: /var/www

    db:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
        ports:
            - 3306:3306
        volumes:
            - mysql_data:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        depends_on:
            - db
        ports:
            - 8080:80
        environment:
            PMA_HOST: db
            PMA_USER: root
            PMA_PASSWORD: root

    mailhog:
        image: mailhog/mailhog
        ports:
            - "8025:8025"
            - "1025:1025"

volumes:
    mysql_data:
